# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 14:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0002_auto_20160131_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_categ_num', models.IntegerField(blank=True, null=True)),
                ('b_title', models.CharField(max_length=20)),
                ('b_contnet', models.CharField(max_length=500)),
                ('b_published_date', models.DateTimeField(blank=True, null=True)),
                ('b_hit', models.IntegerField(default=0)),
                ('tag', tagging.fields.TagField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Board_C',
            fields=[
                ('b_categ_num', models.IntegerField(primary_key=True, serialize=False)),
                ('b_categ_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('company_scale', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company_select',
            fields=[
                ('comp_selnum', models.IntegerField(primary_key=True, serialize=False)),
                ('company_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Company_info')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_form',
            fields=[
                ('emplo_fnum', models.IntegerField(primary_key=True, serialize=False)),
                ('emplof_info', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inter',
            fields=[
                ('inter_num', models.IntegerField(primary_key=True, serialize=False)),
                ('inter_pay_method', models.CharField(max_length=10)),
                ('inter_credit_com', models.CharField(max_length=10, null=True)),
                ('inter_credit_num', models.IntegerField(null=True)),
                ('inter_approve_date', models.DateTimeField(auto_now_add=True)),
                ('inter_depositless_name', models.CharField(max_length=10, null=True)),
                ('inter_depositless_date', models.DateTimeField(auto_now_add=True)),
                ('inter_depositless_bank', models.CharField(max_length=10, null=True)),
                ('inter_deposit_date', models.DateTimeField(auto_now_add=True)),
                ('inter_payamount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Interview_apply',
            fields=[
                ('inter_apply_num', models.IntegerField(primary_key=True, serialize=False)),
                ('work', models.CharField(max_length=50)),
                ('comp_selnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Company_select')),
                ('emplo_fnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Employee_form')),
            ],
        ),
        migrations.CreateModel(
            name='Interview_state',
            fields=[
                ('interv_snum', models.IntegerField(primary_key=True, serialize=False)),
                ('intervs_info', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member_info',
            fields=[
                ('mem_num', models.IntegerField(primary_key=True, serialize=False)),
                ('mem_id', models.CharField(max_length=20)),
                ('mem_pw', models.CharField(max_length=20)),
                ('mem_gender', models.CharField(max_length=2)),
                ('mem_birth', models.CharField(max_length=10)),
                ('mem_hp', models.CharField(max_length=20)),
                ('mem_email', models.CharField(max_length=50)),
                ('mem_add', models.CharField(max_length=200)),
                ('mem_name', models.CharField(max_length=20)),
                ('mem_rank', models.CharField(max_length=10)),
                ('mem_div', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Member_occupation',
            fields=[
                ('mem_occ_num', models.IntegerField(primary_key=True, serialize=False)),
                ('mem_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Member_info')),
            ],
        ),
        migrations.CreateModel(
            name='Mento_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='')),
                ('mento_career', models.CharField(max_length=3)),
                ('mento_proof_doc', models.FileField(upload_to='')),
                ('mem_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Member_info')),
            ],
        ),
        migrations.CreateModel(
            name='Mr_Wish',
            fields=[
                ('mr_wish_num', models.IntegerField(primary_key=True, serialize=False)),
                ('mem_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Member_info')),
            ],
        ),
        migrations.CreateModel(
            name='Mrapply',
            fields=[
                ('mrapply_num', models.IntegerField(primary_key=True, serialize=False)),
                ('mr_pay_method', models.CharField(max_length=10)),
                ('mr_credit_com', models.CharField(max_length=10, null=True)),
                ('mr_credit_num', models.IntegerField(null=True)),
                ('mr_approve_date', models.DateTimeField(auto_now_add=True)),
                ('mr_depositless_name', models.CharField(max_length=10, null=True)),
                ('mr_depositless_date', models.DateTimeField(auto_now_add=True)),
                ('mr_depositless_bank', models.CharField(max_length=10, null=True)),
                ('mr_deposit_date', models.DateTimeField(auto_now_add=True)),
                ('mr_payamount', models.IntegerField()),
                ('mr_wish_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Mr_Wish')),
            ],
        ),
        migrations.CreateModel(
            name='Mrapply_State',
            fields=[
                ('mrapply_con', models.IntegerField(primary_key=True, serialize=False)),
                ('mrapply_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mtr_daily_report',
            fields=[
                ('mtr_daily_num', models.IntegerField(primary_key=True, serialize=False)),
                ('mtr_date', models.DateField(auto_now_add=True)),
                ('mtr_answer', models.CharField(blank=True, max_length=500, null=True)),
                ('mtr_content', models.CharField(blank=True, max_length=500, null=True)),
                ('mrapply_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Mrapply')),
            ],
        ),
        migrations.CreateModel(
            name='Mtr_info',
            fields=[
                ('mtr_num', models.IntegerField(primary_key=True, serialize=False)),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('mtr_content', models.CharField(blank=True, max_length=500, null=True)),
                ('fixed_people', models.IntegerField()),
                ('mem_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Mento_info')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation_type',
            fields=[
                ('occ_num', models.IntegerField(primary_key=True, serialize=False)),
                ('occ_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('r_num', models.IntegerField(primary_key=True, serialize=False)),
                ('mrapply_num', models.IntegerField(blank=True, null=True)),
                ('mr_title', models.CharField(max_length=20, null=True, verbose_name='멘티이름')),
                ('mto_name', models.CharField(max_length=20, null=True, verbose_name='멘토이름')),
                ('r_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='조회수')),
                ('r_content', models.CharField(max_length=500, null=True, verbose_name='내용')),
                ('r_image', models.ImageField(null=True, upload_to='')),
                ('r_like', models.IntegerField(blank=True, default=0, null=True, verbose_name='좋아요 수')),
                ('r_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='작성날짜')),
            ],
        ),
        migrations.CreateModel(
            name='Self_introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_intro_cont', models.CharField(max_length=2000)),
                ('portfolio_file', models.FileField(upload_to='')),
                ('inter_occupation1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Occupation_type')),
                ('inter_occupation2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inter_occupation1', to='photo.Occupation_type')),
                ('inter_occupation3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inter_occupation2', to='photo.Occupation_type')),
                ('mem_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Member_info')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_num', models.IntegerField(primary_key=True, serialize=False)),
                ('mtr_lesson', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='mtr_info',
            name='occ_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Occupation_type'),
        ),
        migrations.AddField(
            model_name='mtr_daily_report',
            name='mtr_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.State'),
        ),
        migrations.AddField(
            model_name='mrapply',
            name='mrapply_con',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.State'),
        ),
        migrations.AddField(
            model_name='mr_wish',
            name='mtr_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Mtr_info'),
        ),
        migrations.AddField(
            model_name='member_occupation',
            name='occ_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Occupation_type'),
        ),
        migrations.AddField(
            model_name='interview_apply',
            name='interv_snum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.Interview_state'),
        ),
        migrations.AddField(
            model_name='inter',
            name='inter_apply_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Interview_apply'),
        ),
        migrations.AddField(
            model_name='company_select',
            name='mem_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Member_info'),
        ),
        migrations.AddField(
            model_name='company_info',
            name='company_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Member_info'),
        ),
        migrations.AddField(
            model_name='company_info',
            name='jobcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Occupation_type'),
        ),
        migrations.AddField(
            model_name='board',
            name='board_c',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.Board_C'),
        ),
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
