# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20180515_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='mrapply_num',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='photo.Mrapply'),
            preserve_default=False,
        ),
    ]
