# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_auto_20180516_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='b_auth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.Member_info'),
        ),
        migrations.AddField(
            model_name='board',
            name='b_password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='b_re_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='b_re_step',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='b_ref',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
