# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0010_auto_20180517_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_re_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='b_re_step',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='b_ref',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
