# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0013_auto_20180517_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mrapply',
            old_name='mrapply_con',
            new_name='state_num',
        ),
        migrations.AlterField(
            model_name='board',
            name='b_re_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='b_re_step',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='b_ref',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
